version: '3'
services:
  ghost-blog:
    image: ghost:1-alpine
    ports:
      - 3001:2368
    depends_on:
      - db
    restart: always
    environment:
      database__client: mysql
      database__connection__database: ghost
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
    networks:
      - my-network 
  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - dados:/var/lib/mysql
    networks:
      - my-network 
volumes:
  dados:
networks:
  my-network: 


    